### PR TITLE
Update minimum PHP to 7.4, update `laminas/laminas-coding-standard` to `~2.4.0`, restrict `composer` `<2.3.0` in renovate

### PR DESCRIPTION
**Pull request by internalsystemerror**
|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | no
| BC Break      | no
| New Feature   | no
| RFC           | no
| QA            | yes

### Description

This PR:
- Updates the minimum supported PHP version to 7.4
-  Updates `laminas/laminas-coding-standard` to `~2.4.0` (closes https://github.com/laminas/laminas-dependency-plugin/pull/45).
- Restricts renovate from updating `composer-api-plugin` or `composer/composer` beyond `<2.3.0` (should allow https://github.com/laminas/laminas-dependency-plugin/pull/45 to proceed once regenerated)

### CODE REVIEW

**Review by gsteel — APPROVED** [review]
LGTM - No CI for obvious reasons

**Comment by internalsystemerror** [comment]
@gsteel im a bit confused, what are the obvious reasons? I was expecting those to have ran.

**Comment by gsteel** [comment]
No PHP code was touched so in my experience, CS checks and tests don't run - I thought that's how it was supposed to work 🤷‍♂️

**Comment by internalsystemerror** [comment]
Oh right, I wasn't aware of that, even if composer packages were updated? Good to know anyway.

**Pull request merged**
